name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # 在推送到 main 或 master 分支时触发
    # 如果只想在特定文件更改时触发，可以取消注释下面的 paths
    # paths:
    #   - 'cmd/**'
    #   - 'pkg/**'
    #   - 'Dockerfile'
    #   - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-duckdns